//MODELO
  /*{
      id: 0,
      discount: 0,
      cover: "./images/agricultura/",
      name: "",
      price: 0,
      cat: "",
      desc: "",
    },*/

const Data = {
  productItems: [
    {
      id: 1,
      discount: 0,
      cover: "./images/agricultura/rocadeira1.png",
      name: "Roçadeira SBC 227D - 25,4 cc",
      price: 2080,
      cat: "equipamentos",
      desc: "Versátil, robusta, leve e potente, o modelo SBC 227D é ideal para a manutenção e acabamento de jardins, gramados, capins e ervas daninhas pouco densas em residenciais e sítios. Conta com um arranque fácil do motor e sistema antivibração que proporcionam trabalho rápido, prático e seguro. A base do guidão giratório, facilita o transporte e armazenamento do equipamento.",
    },
    {
      id: 2,
      discount: 5,
      cover: "./images/agricultura/rocadeira2.png",
      name: "Roçadeira Profissional 2T 52CC VR520H VULCAN",
      price: 825,
      cat: "equipamentos",
      desc: "Roçadeira profissional VR520H da Vulcan é desenvolvida para trabalhos de alta intensidade e desempenho, eficiente para trabalhos diários como corte de grama e manutenção de jardins residenciais.",
    },
    {
      id: 3,
      discount: 20,
      cover: "./images/agricultura/dosador1.png",
      name: "Dosador Universal de Líquidos com Tubo Aplicador",
      price: 50,
      cat: "equipamentos",
      desc: "O acessório Dosador Universal de Líquidos foi desenvolvido para situações que exijam alta precisão na dosagem de produtos químicos em geral, permitindo obter facilmente regulagens precisas de dosagens, na faixa de 2 a 25 ml, por acionamento.",
    },
    {
      id: 4,
      discount: 15,
      cover: "./images/agricultura/pulverizador1.png",
      name: "Pulverizador de Compressão Prévia 4,7L",
      price: 175,
      cat: "equipamentos",
      desc: "Ideal para a aplicação de inseticidas, herbicidas, adubos foliares, conservantes em madeira, detergentes, produtos de limpeza, desengraxantes para automóveis, motos e máquinas em geral, assim como para sanitização de residências, hotéis, restaurantes etc.",
    },
    {
      id: 5,
      discount: 0,
      cover: "./images/agricultura/pulverizador2.png",
      name: "Pulverizador Costal Balance 20L",
      price: 420,
      cat: "equipamentos",
      desc: "O Balance alia as tradicionais qualidades dos Pulverizadores Guarany, com soluções inéditas no design, funcionamento, versatilidade e durabilidade.",
    },

    {
      id: 6,
      discount: 44,
      cover: "./images/agricultura/soprovarredor.png",
      name: "Soprovarredor Costal Motorizado - G59 - 59,2 cc",
      price: 2100,
      cat: "equipamentos",
      desc: "Complementando a linha de motorizados, o equipamento possui em seu DNA a tradicional qualidade da marca Guarany aliada a ergonomia, facilidade no uso e alta capacidade de sopro, representando o melhor custo-benefício para sua necessidade.",
    },



    {
      id: 7,
      discount: 15,
      cover: "./images/agricultura/alface.png",
      name: "Alface Veneranda",
      price: 44.55,
      cat: "sementes",
      desc: "",
    },
    {
      id: 8,
      discount: 0,
      cover: "./images/agricultura/tomate.png",
      name: "Tomate Afonso",
      price: 20.90,
      cat: "sementes",
      desc: "",
    },
    {
      id: 9,
      discount: 0,
      cover: "./images/agricultura/melancia.png",
      name: "Melancia Crimson Sweet",
      price: 39.15,
      cat: "sementes",
      desc: "",
    },
    {
      id: 10,
      discount: 0,
      cover: "./images/agricultura/abobrinha.png",
      name: "Abobrinha Caserta Italiana",
      price: 55.35,
      cat: "sementes",
      desc: "",
    },
    {
      id: 11,
      discount: 10,
      cover: "./images/agricultura/berinjela.png",
      name: "Berinjela Embu",
      price: 89.10,
      cat: "sementes",
      desc: "",
    },
    {
      id: 12,
      discount: 0,
      cover: "./images/agricultura/repolho.png",
      name: "Repolho Mini Yakko",
      price: 189,
      cat: "sementes",
      desc: "",
    },


    {
      id: 13,
      discount: 0,
      cover: "./images/agricultura/fertilizante1.png",
      name: "Fertilizante Hidrossolúvel Para Horta, Flores E Frutas Vithal - 400g",
      price: 28.50,
      cat: "fertilizantes",
      desc: "",
    },
    {
      id: 14,
      discount: 8,
      cover: "./images/agricultura/fertilizante2.png",
      name: "Fertilizante Haifa Cal Gg Haifa - 25kg",
      price: 135,
      cat: "fertilizantes",
      desc: "",
    },
    {
      id: 15,
      discount: 0,
      cover: "./images/agricultura/fertilizante3.png",
      name: "Fertilizante Foliar K 400 Forplant - 2 Kg",
      price: 54.29,
      cat: "fertilizantes",
      desc: "",
    },
    {
      id: 16,
      discount: 5,
      cover: "./images/agricultura/fertilizante4.png",
      name: "Fertilizante Orgânico Biokashi Biomix - 25kg",
      price: 125.59,
      cat: "fertilizantes",
      desc: "",
    },



    {
      id: 17,
      discount: 20,
      cover: "./images/agricultura/tubo gotejador.png",
      name: "Tubo Gotejador Streamline X 16080 1.60 L/h 30cm 2500m - Netafim",
      price: 1200,
      cat: "irrigação",
      desc: "",
    },
    {
      id: 18,
      discount: 0,
      cover: "./images/agricultura/aspersor.png",
      name: "Aspersor D-net 8550 2.9 + 1.8 680 L/h - Netafim",
      price: 24.28,
      cat: "irrigação",
      desc: "",
    },
    {
      id: 19,
      discount: 0,
      cover: "./images/agricultura/botão gotejador.png",
      name: "Botão Gotejador Pcj Lcnl Cilíndrico 4 L/h - Netafim",
      price: 0.35,
      cat: "irrigação",
      desc: "",
    },
    {
      id: 20,
      discount: 0,
      cover: "./images/agricultura/filtro.png",
      name: "Filtro Plástico Tela 1 Tavlit - Netafi",
      price: 30.72,
      cat: "irrigação",
      desc: "",
    },

  
  ],
}
export default Data
